import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Badge, Group, Text, Container, Title, ActionIcon } from '@mantine/core';
import { IconFileText, IconDownload, IconEye } from '@tabler/icons-react';
import { notifications } from '@mantine/notifications';
import DataTable from '../../DataTable/DataTable';

interface LabReport {
  id: number;
  orderId: number;
  patientName: string;
  testNames: string;
  reportPdf: string;
  generatedBy: string;
  generatedAt: string;
  status: string;
}

const PAGE_SIZE = 10;

export default function LabReportsGrid() {
  const [reports, setReports] = useState<LabReport[]>([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [search, setSearch] = useState('');
  const navigate = useNavigate();

  const fetchData = async () => {
    try {
      // Mock data for now
      const mockReports: LabReport[] = [
        {
          id: 1,
          orderId: 1001,
          patientName: 'John Doe',
          testNames: 'Complete Blood Count, Lipid Profile',
          reportPdf: 'report_1001.pdf',
          generatedBy: 'Lab Admin',
          generatedAt: '2024-01-15T16:00:00',
          status: 'GENERATED'
        },
        {
          id: 2,
          orderId: 1002,
          patientName: 'Jane Smith',
          testNames: 'Thyroid Function Test',
          reportPdf: 'report_1002.pdf',
          generatedBy: 'Lab Admin',
          generatedAt: '2024-01-15T17:30:00',
          status: 'DELIVERED'
        }
      ];
      
      const filteredData = search 
        ? mockReports.filter(report => 
            report.patientName.toLowerCase().includes(search.toLowerCase()) ||
            report.testNames.toLowerCase().includes(search.toLowerCase())
          )
        : mockReports;
      
      const startIndex = (page - 1) * PAGE_SIZE;
      const endIndex = startIndex + PAGE_SIZE;
      setReports(filteredData.slice(startIndex, endIndex));
      setTotalPages(Math.ceil(filteredData.length / PAGE_SIZE));
    } catch (error) {
      notifications.show({
        title: 'Error',
        message: 'Failed to load lab reports',
        color: 'red',
      });
    }
  };

  useEffect(() => {
    fetchData();
  }, [page, search]);

  const handleDownload = (report: LabReport) => {
    notifications.show({
      title: 'Download',
      message: `Downloading ${report.reportPdf}`,
      color: 'blue',
    });
  };

  const getStatusBadge = (status: string) => {
    const colors = { 
      GENERATED: 'blue', 
      DELIVERED: 'green', 
      PENDING: 'orange'
    };
    return <Badge color={colors[status as keyof typeof colors] || 'gray'}>{status}</Badge>;
  };

  return (
    <Container size="xl" className="py-4">
      <Title order={2} className="text-gray-800 mb-6">
        Lab Reports Management
      </Title>
      <DataTable<LabReport>
        data={reports}
        columns={[
          { 
            key: 'orderId', 
            label: 'Order ID',
            render: (report) => (
              <Text fw={500}>#{report.orderId}</Text>
            )
          },
          { 
            key: 'patientName', 
            label: 'Patient',
            render: (report) => <Text fw={500}>{report.patientName}</Text>
          },
          { 
            key: 'testNames', 
            label: 'Tests',
            render: (report) => (
              <Group gap="xs">
                <IconFileText size={14} />
                <Text size="sm" truncate style={{ maxWidth: 200 }}>
                  {report.testNames}
                </Text>
              </Group>
            )
          },
          { 
            key: 'generatedBy', 
            label: 'Generated By',
            render: (report) => <Text size="sm">{report.generatedBy}</Text>
          },
          { 
            key: 'generatedAt', 
            label: 'Generated At',
            render: (report) => (
              <Text size="sm">
                {new Date(report.generatedAt).toLocaleString()}
              </Text>
            )
          },
          { 
            key: 'status', 
            label: 'Status',
            render: (report) => getStatusBadge(report.status)
          },
          { 
            key: 'actions', 
            label: 'Actions',
            render: (report) => (
              <Group gap="xs">
                <ActionIcon
                  variant="light"
                  color="blue"
                  onClick={() => handleDownload(report)}
                >
                  <IconDownload size={14} />
                </ActionIcon>
                <ActionIcon
                  variant="light"
                  color="green"
                  onClick={() => navigate(`/admin/lab/reports/view/${report.id}`)}
                >
                  <IconEye size={14} />
                </ActionIcon>
              </Group>
            )
          }
        ]}
        onView={(report) => navigate(`/admin/lab/reports/view/${report.id}`)}
        onAdd={() => navigate('/admin/lab/reports/generate')}
        canExport
        pagination={{ page, total: totalPages, onPageChange: setPage }}
        search={{ value: search, onChange: setSearch }}
        exportData={reports}
        exportFilename="lab-reports"
      />
    </Container>
  );
}